version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "127.0.0.1:5433:5432"  # port 5433
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage
    networks:
      - retail_network  # Isolated network for security

volumes:
  pgdata:

networks:
  retail_network:
    driver: bridge
